// Generated by CoffeeScript 2.7.0
(function() {
  var fib, i, j;

  fib = function(n) {
    var i, j, n1, n2, ref, sum;
    n1 = 1;
    n2 = 1;
    sum = 0;
    if (n === 0) {
      return 0;
    } else if (n === 1 || n === 2) {
      return 1;
    } else {
      for (i = j = 2, ref = n; (2 <= ref ? j < ref : j > ref); i = 2 <= ref ? ++j : --j) {
        sum = n1 + n2;
        console.log(n1, n2, sum);
        n1 = n2;
        n2 = sum;
      }
    }
    return sum;
  };

  for (i = j = 0; j < 10; i = ++j) {
    console.log('fib', i, fib(i));
  }

}).call(this);
